### ISSUE TITLE
Different stickers send Jinx

### ISSUE THREAD

**Issue by GreepTheSheep** [ArendelleOdyssey/discord-bot#54]
Add a condition to check differences on stickers

**Comment by Ymke-N** [comment]
Okay I've done some looking, and I've got some bad new regarding stickers
The content that stickers sent is "". So when you compare 2 stickers its: "" == "" > true, always
So I'd say, make an extra check that when its 2 stickers, aka two empty messages, then it doesnt send a jinx
I can't find anything in the discord documentation on how to compare stickers atm

**Comment by GreepTheSheep** [comment]
Add a condition to skip the jinx if the content is empty, in any cases
